workflows:
    ios-workflow:
        name: Workflow
        max_build_duration: 120
        instance_type: mac_mini_m2
        integrations:
            app_store_connect: Key
        environment:
            ios_signing:
               distribution_type: app_store
               bundle_identifier: com.afireappnotes.app
            vars:
              BUNDLE_ID: com.afireappnotes.app
              XCODE_PROJECT: "FireAppNotes.xcodeproj"
              XCODE_SCHEME: "FireAppNotes"
              APP_STORE_APPLE_ID: 6749571289
            xcode: latest
        scripts:
        - name: Set up provisioning profiles settings on Xcode project
          script: xcode-project use-profiles

        - name: Resolve Swift packages
          script: |
            xcodebuild -resolvePackageDependencies \
            -project "$CM_BUILD_DIR/$XCODE_PROJECT"

        - name: Build ipa for distribution
          script: |
            xcode-project build-ipa \
            --project "$CM_BUILD_DIR/$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
        artifacts:
        - build/ios/ipa/*.ipa
        - /tmp/xcodebuild_logs/*.log
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
        publishing:
          app_store_connect:
            auth: integration


